# Gate teleportation
$\renewcommand{\coloneqq}{\mathrel{:=}}$

In [44]:
import numpy as np
import piquasso as pq

dB = 77
SQUEEZING = np.log(10)/20*dB
HBAR = 2


#Displacement values for preparing coherent states
a = 5
b = 3
alpha = a + b*1j

c = 2
d = 7
beta = c + d*1j

One can implement $$\mathrm{G}_{jk}(\mathbf{\theta})\coloneqq B^{\dagger}_{jk}V_j(\theta_1, \theta_3)V_k(\theta_2, \theta_4)
B_{jk}$$
$$V_i(\theta_l, \theta_h)=R_{i}(\theta^{h,l}_+)S_{i}(\ln\tan\theta^{h,l}_-, \pi)R_{i}(\theta^{h,l}_+)$$
with some noise and know displacement  
$$D_j(\theta_1,\theta_3,m_1,m_3) \\ 
D_k(\theta_2,\theta_4,m_2,m_4)$$
where $m_i$ is a measurement result of $\hat{x}_{\theta_i}$.

Noise decreases as we increase the the `SQUEEZING` parameter in the EPR state preparation.

$\theta_\pm^{h,l}\coloneqq\frac{\theta_h\pm\theta_l}{2}$
$\theta\coloneqq(\theta_1,\theta_2,\theta_3,\theta_4)$

$$D_i(\theta_l,\theta_h,m_l,m_h) = D\left[ \frac{e^{i\theta_h}m_l+e^{i\theta_l}m_h}{\sin(\theta_l - \theta_h)} \right]$$

Two single mode identical phaseshifters or squeezers commute with the 50:50 beamsplitter: $$B_{jk}R_j(\phi)R_k(\phi)=R_j(\phi)R_k(\phi)B_{jk}$$ $$B_{jk}S_j(r)S_k(r)=S_j(r)S_k(r)B_{jk}$$
 
Consequenty, the beamsplitters should be undone manually, if two gates are not identical.


An other useful identity is $B_{nm}^\dagger=B_{mn}$, as a result 50:50 beamsplitters can be undone by changing the order of modes. 





#### Phaseshifter
To teleport phaseshifters with a parameter $\phi$ parameters $\theta$ should be choosen like
$$ \theta_+^{3,1}\coloneqq \theta_+^{4,2}\coloneqq \frac{\phi}{2} $$
$$ \theta_-^{3,1}\coloneqq \theta_-^{4,2}\coloneqq \frac{\pi}{4} $$
$$ \theta_3 = \theta_4 = \theta_+^{3,1} + \theta_-^{3,1} = \frac{\phi}{2} +\frac{\pi}{4}$$
$$ \theta_1 = \theta_2 = \theta_+^{3,1} + \theta_-^{3,1} = \frac{\phi}{2} -\frac{\pi}{4}$$
$$\psi\coloneqq\theta_1+\frac{\pi}{2}=\theta_2+\frac{\pi}{2}=\theta_3=\theta_4$$
and $$\theta_+^{3,1}=\theta_+^{4,2}=\psi- \frac{\pi}{4}$$
the squeezers become identities ($\theta_-^{3,1}=\pi/4 \implies\tan\theta_-^{3,1}=1$), so $G(\theta)=R_{j}(\phi)R_{k}(\phi)$




In [45]:
# two mode identical phaseshifter teleport setup
def id_phaseshifter(phi):
    psi = (phi+np.pi/2)/2
    return [psi-np.pi/2, psi-np.pi/2, psi, psi]

Teleporting two different phaseshifters is quite similar except the sandwiching beamsplitters should be removed. 
$$ \psi_1\coloneqq\theta_3=\theta_1+\pi/2 
\\
\psi_2\coloneqq\theta_4=\theta_2+\pi/2 $$
 and $\phi_i\coloneqq2\psi_i- \frac{\pi} {2}, (i=1,2)$, the squeezers become identities (see above), $$G(\theta)=B^{\dagger}_{jk}R_{j}(\phi_1)R_{k}(\phi_2)B_{jk}$$

In [46]:
# different valued phaseshifter teleport setup
def arb_phaseshiter(phi1, phi2):
    #Corrections 
    #Before: pq.Beamsplitter5050() modes in reverse order
    #After: pq.Beamsplitter5050()
    psi1 = (phi1+np.pi/2)/2
    psi2 = (phi2+np.pi/2)/2
    return [psi1-np.pi/2, psi2-np.pi/2, psi1, psi2]

#### Squeezing
To implement two identical squeezers with parameter $r$ one should choose $$-\theta_1\coloneqq-\theta_2\coloneqq\theta_3\coloneqq\theta_4 \coloneqq 
\arctan e^{r}=\phi$$
We get
$$\theta_-^{4,2}=\theta_-^{3,1} = \phi$$
for squeezing parameter and phaseshiter parameters trivially become
$$\theta_+^{4,2}=\theta_+^{3,1} = 0$$
Indeed $r=\ln\tan\phi$ so $\mathrm{G}$ simplifies to $$S_{j}(r,\pi)S_{k}(r,\pi)$$

In [47]:
# two mode identical squeezing teleport setup
def id_squeezing(r):
    #r = 3
    phi = np.arctan(np.exp(r))
    return [-phi, -phi, phi, phi]

In order to implement two different squeezers one should choose 
$$\arctan e^{r_1}=\phi_1\coloneqq\theta_3=-\theta_1$$
$$\arctan e^{r_2}=\phi_2\coloneqq\theta_4=-\theta_2$$
 and $r_i=\ln\tan\phi_i, (i=1,2)$, as G simplifies to $$B^{\dagger}_{jk}S_{j}(r_1,\pi)S_{k}(r_2,\pi)B_{jk}$$

In [48]:
# different valued squeezing
def arb_squeezing(r1, r2):
    #Corrections 
    #Before: pq.Beamsplitter5050() modes in reverse order
    #After: pq.Beamsplitter5050()
    phi1 = np.arctan(np.exp(r1))
    phi2 = np.arctan(np.exp(r2))
    return [-phi1, -phi2, phi1, phi2]



#### Beamsplitter

$\theta_- \coloneqq \psi$
$\theta_+ \coloneqq -\pi/2$ 

We choose

$$\theta_1 \coloneqq \frac{\theta_++\theta_-}{2} = -\frac{\pi}{4}+\frac{\psi}{2}
\\
\theta_2 \coloneqq \frac{\theta_+-\theta_-}{2} = -\frac{\pi}{4}-\frac{\psi}{2}
\\
\theta_3 \coloneqq \theta_1+\frac{\pi}{2}
\\
\theta_4 \coloneqq \theta_2+\frac{\pi}{2}$$

It gives
$$\theta_-^{3,1} = \frac{\theta_1+\pi/2-\theta_1}{2} = \frac{\pi}{4}
\\
\theta_-^{4,2} = \frac{\theta_2+\pi/2-\theta_2}{2} = \frac{\pi}{4}$$
Hence squeezings become trivial
$$\tan\frac{\pi}{4}=1 \implies S(-\ln\tan\frac{\pi}{4})=\mathbf{I}$$


For phaseshifter parameters we obtain 
$$\theta_+^{3,1} = \frac{\theta_1+\pi/2+\theta_1}{2} = \theta_1+\frac{\pi}{4} = \frac{\psi}{2}
\\
\theta_+^{4,2} = \frac{\theta_2+\pi/2+\theta_2}{2} = \theta_2+\frac{\pi}{4} = -\frac{\psi}{2}$$

The teleported gate:
$$\mathrm{G}(\theta) = B^{\dagger}_{jk}R_{j}(\psi)R_{k}(-\psi)B_{jk}= \\ = B_{jk}(\psi,-\frac{\pi}{2})$$
With before and after phase corrections we get get a fully parametrised beamsplitter

$$
\boxed{
\begin{aligned}
R_k(\frac{\pi}{2}+\phi)G(\theta)R_k(-\frac{\pi}{2}-\phi) = \\ =
R_k(\frac{\pi}{2}+\phi)B_{jk}(\psi,-\frac{\pi}{2})R_k^\dagger(\frac{\pi}{2}+\phi) = \\ =
B_{jk}(\psi,\phi)
\end{aligned}
}
$$


Using $R_m(\alpha)B_{nm}(\theta, \phi)R_m^{\dagger}(\alpha)=B_{nm}(\theta, \phi+\alpha)$ idenity.

In [49]:
def real_beamsplitter(psi):
    # Corrections
    # Before pq.Phaseshifter(-np.pi/2-phi) on the 2nd mode
    # After pq.Phaseshifter(np.pi/2+phi) on the 2nd mode
    theta_minus_BS = psi
    theta_plus_BS = -np.pi/2
    theta1 = (theta_plus_BS+theta_minus_BS)/2
    theta2 = (theta_plus_BS-theta_minus_BS)/2
    return [theta1, theta2, theta1+np.pi/2, theta2+np.pi/2]




Parameters are set here. The functions `id_phaseshifter(phi)`, 
`id_squeezing(r)`, `arb_squeezing(r1, r2)`,
`real_beamsplitter(psi)` are used set `thetas` ($\theta$) accordingly. 

In [50]:
gamma = np.pi/11

phi = 3*np.pi/7

thetas = real_beamsplitter(gamma)


In [51]:
# General case
def teleported_gates_program(theta1, theta2, theta3, theta4):

    inst = [pq.Beamsplitter5050().on_modes(0, 1)]
    inst.extend(teleported_gates(theta1, theta3, 0))
    inst.extend(teleported_gates(theta2, theta4, 1))
    inst.extend([pq.Beamsplitter5050().on_modes(1, 0)])
    return pq.Program(instructions=inst)



def teleported_gates(theta_h, theta_l, mode_index):

    plus_minus = lambda x, y: ((x+y)/2, (x-y)/2)
    theta_plus, theta_minus = plus_minus(theta_l, theta_h)
    rr1 = np.log(np.tan(theta_minus))
    breakpoint()
    return [
        pq.Phaseshifter(theta_plus).on_modes(mode_index),
        pq.Squeezing(-rr1).on_modes(mode_index),
        pq.Phaseshifter(theta_plus).on_modes(mode_index)
    ]


In [ ]:
# Teleportation circuit
def gate_teleport_program(theta1, theta2, theta3, theta4):
    return pq.Program(instructions=gate_teleport_instructions(theta1, theta2, theta3, theta4))


def gate_teleport_instructions(theta1, theta2, theta3, theta4, mode_index = 0):
    
    def displacementFeedForward(x, theta_h, theta_l, i = 0):
        ml, mh = x[-4-2*i], x[-2-2*i]
        D_imag = (np.exp(1j*theta_h)*ml + np.exp(1j*theta_l)*mh)/(np.sin(theta_h - theta_l))
        D = D_imag/np.sqrt(HBAR)
        return D
    
    def displacement_j(x):
        return displacementFeedForward(x, theta1, theta3, 2)
    def displacement_k(x):
        return displacementFeedForward(x, theta2, theta4)
    

    def to_polar(a):
        return [np.abs(a), np.angle(a)]

    def feedforward_j(x):
        D = (displacement_j(x) + displacement_k(x))/np.sqrt(2)
        return to_polar(D)

    
    def feedforward_k(x):
        D = (-displacement_j(x) + displacement_k(x))/np.sqrt(2)
        return to_polar(D)



    return [

        #0 - -> input1 M:theta3
        #1 - x squeezing M:theta1
        #2 - p squeezing -> output1
        #3 - -> input2 M:theta4
        #4 - x squeezing M:theta2
        #5 - p squeezing -> output2

        #One mode gate teleportation setup
        pq.Squeezing(SQUEEZING,0).on_modes(mode_index+1),
        pq.Squeezing(SQUEEZING,np.pi).on_modes(mode_index+2),
        pq.Beamsplitter5050().on_modes(mode_index+1, mode_index+2),
        pq.Beamsplitter5050().on_modes(mode_index, mode_index+1),


        #One mode gate teleportation setup
        pq.Squeezing(SQUEEZING, 0).on_modes(mode_index+4),
        pq.Squeezing(SQUEEZING, np.pi).on_modes(mode_index+5),
        pq.Beamsplitter5050().on_modes(mode_index+4, mode_index+5),
        pq.Beamsplitter5050().on_modes(mode_index+3, mode_index+4),

        pq.Beamsplitter5050().on_modes(mode_index, mode_index+3),
        pq.Beamsplitter5050().on_modes(mode_index+1, mode_index+4),



        pq.HomodyneMeasurement(phi=-theta3+np.pi/2, z=1e-5).on_modes(mode_index),
        pq.HomodyneMeasurement(phi=-theta1+np.pi/2, z=1e-5).on_modes(mode_index+1),
        pq.HomodyneMeasurement(phi=-theta4+np.pi/2, z=1e-5).on_modes(mode_index+3),
        pq.HomodyneMeasurement(phi=-theta2+np.pi/2, z=1e-5).on_modes(mode_index+4),
        
        #Feedforward
        pq.Displacement(lambda x : feedforward_j(x)[0], lambda x : feedforward_j(x)[1]).on_modes(mode_index+2),
        pq.Displacement(lambda x : feedforward_k(x)[0], lambda x : feedforward_k(x)[1]).on_modes(mode_index+5),

        #Phase corrections
        pq.Phaseshifter(-np.pi/2).on_modes(mode_index+2),
        pq.Phaseshifter(-np.pi/2).on_modes(mode_index+5)
    ]


In [53]:
def prep():

    r1 = np.abs(alpha)
    phi1 = np.angle(alpha)
    r2 = np.abs(beta)
    phi2 = np.angle(beta)
    return pq.Program(instructions=[pq.Vacuum().on_modes(0, 1), pq.Displacement(r1, phi1).on_modes(0), pq.Displacement(r2, phi2).on_modes(1)])

with pq.Program() as TwoModeTest:
    pq.Q(0, 1) | prep()
    # general case
    #pq.Q(0, 1) | teleported_gates_program(*thetas)

    # two mode identical phaseshifter teleport
    #pq.Q(0) | pq.Phaseshifter(alfa)
    #pq.Q(1) | pq.Phaseshifter(alfa)

    # two mode identical squeezing teleport
    #pq.Q(0) | pq.Squeezing(r, np.pi)
    #pq.Q(1) | pq.Squeezing(r, np.pi)

    # different valued phaseshifter
    #pq.Q(0, 1) | pq.Beamsplitter5050()
    #pq.Q(0) | pq.Phaseshifter(alpha)
    #pq.Q(1) | pq.Phaseshifter(beta)
    #pq.Q(1, 0) | pq.Beamsplitter5050()


    # different valued squeezing
    #pq.Q(0, 1) | pq.Beamsplitter5050()
    #pq.Q(0) | pq.Squeezing(r1, np.pi)
    #pq.Q(1) | pq.Squeezing(r2, np.pi)
    #pq.Q(1, 0) | pq.Beamsplitter5050()
    


    #beamsplitter
    pq.Q(0, 1) | pq.Beamsplitter(t, phi)

    

with pq.Program() as TwoDimClusterGateTeleport:
    pq.Q(0, 1, 2, 3, 4, 5) | pq.Vacuum()
    pq.Q(0, 3) | prep()

    pq.Q(3) | pq.Phaseshifter(-np.pi/2-phi)

    pq.Q(0, 1, 2, 3, 4, 5) | gate_teleport_program(*thetas)

    pq.Q(5) | pq.Phaseshifter(phi+np.pi/2)


### Simulation

In [54]:
config = pq.Config(hbar=HBAR)


def make_simulator(d, seed=1234):
    return pq.GaussianSimulator(
        d=d,
        config=pq.Config(
            hbar=HBAR,
            seed_sequence=seed,
        ),
    )


simulator_1 = make_simulator(2)

result = simulator_1.execute(TwoModeTest, shots=1)
target_state = result.state


teleport_simulator = make_simulator(6)
teleported_result = teleport_simulator.execute(TwoDimClusterGateTeleport,  shots=1)
teleported_state = teleported_result.state



#### Results and errors

Errors $\to 0$ as `SQUEEZING` $\to \infty$

In [55]:
print("Target mean:")
print(target_state.xxpp_mean_vector)

print("Target covariance:")
print(target_state.xxpp_covariance_matrix)



print("Teleported mean:")
print(teleported_state.xxpp_mean_vector)

print("Mean error:")
mean_err = (teleported_state.xxpp_mean_vector - target_state.xxpp_mean_vector)
print(mean_err)
print("Mean error norm: ", np.linalg.norm(mean_err))


print("Cov error:")

cov_err = (teleported_state.xxpp_covariance_matrix - target_state.xxpp_covariance_matrix)
print(cov_err)

print("Covarience error norm: ", np.linalg.norm(cov_err))



Target mean:
[ 5.4987991   2.81687221  5.97795409 16.55573931]
Target covariance:
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
Teleported mean:
[ 5.49915066  2.81638999  5.97848511 16.55533215]
Mean error:
[ 0.00035156 -0.00048222  0.00053102 -0.00040717]
Mean error norm:  0.0008966021463177207
Cov error:
[[ 2.79396772e-08 -5.44783424e-09  3.72529030e-09  1.24343261e-09]
 [-5.44783424e-09  2.84492612e-08  4.14477538e-10 -1.49265807e-09]
 [ 3.72529030e-09  4.14477538e-10  5.58793545e-09  1.81594475e-09]
 [ 1.24343261e-09 -1.49265807e-09  1.81594475e-09  5.07835152e-09]]
Covarience error norm:  4.181627999753134e-08
